language: python
python:
  - 3.6

cache: pip

install:
  - pip install codecov
  - pip install -e .

script:
  - pytest --doctest-modules tests/ --cov=codecov

# Push the results back to codecov
after_success:
  - codecov
