language: python
python:
  - 3.6

cache: pip

install:
  - pip install pytest coverage pytest-cov
  - pip install codecov  # https://blog.travis-ci.com/2019-08-07-extensive-python-testing-on-travis-ci
  - pip install -e .

script:
  - pytest --doctest-modules tests/ lazy_dataset/ --cov=lazy_dataset

after_success:
  - codecov # submit coverage

env:
  - OMP_NUM_THREADS=1 MKL_NUM_THREADS=1
